#!/bin/sh
# postinst script for gooroom-artwork-gnome-flashback
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#/etc/gooroom/adjustments/update-panel-layout.execute
if [ -e /etc/gooroom/adjustments/gooroom-update-panel-layout.execute ]; then
    /etc/gooroom/adjustments/update-panel-layout.execute
fi

glib-compile-schemas /usr/share/glib-2.0/schemas

# /usr/share/applications/mimeapps.list
if [ -e /usr/share/gooroom-artwork-gnome-flashback/mimeapps.list ]; then
    cp /usr/share/gooroom-artwork-gnome-flashback/mimeapps.list /usr/share/applications
    cp /usr/share/gooroom-artwork-gnome-flashback/mimeapps.list /usr/share/applications/gnome-mimeapps.list
    update-desktop-database /usr/share/applications
fi

# update-metacity-navigation.execute
if [ -e /etc/gooroom/adjustments/update-metacity-navigation.execute ]; then
    /etc/gooroom/adjustments/update-metacity-navigation.execute
fi

exit 0
